steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mlops6-410910/testing', 'train.Dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mlops6-410910/testing']