version: "3"
services:
  trainer:
    image: trainer:latest
    build:
      context: .
      dockerfile: dockerfiles/train_model.dockerfile
    volumes:      
      - ./models:/models
  predict:
    image: predict:latest
    build:
      context: .
      dockerfile: dockerfiles/predict_model.dockerfile
    volumes:      
      - ./models:/models
