output_dir: models/
wandb_logging: disabled

optimizer: Adam
lr: 2e-5
epochs: 2
checkpoints:  True
fast_dev_run: False

per_device_train_batch_size: 16
per_device_eval_batch_size: 16
weight_decay: 0.01

limit_train_batches: 0.1
limit_val_batches: 0.1
limit_test_batches: 0.1

mixed_precision: "32-true"