output_dir: models/
optimizer: Adam
lr: 2e-5
epochs: 2

per_device_train_batch_size: 16
per_device_eval_batch_size: 16
weight_decay: 0.01

limit_train_batches: 0.2
limit_val_batches: 1.0

mixed_precision: "16-true"